name: .NET CI workflow
on:
  push:
    branches:
        - main

jobs:
  E-shop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Web/
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Code Quality analysis
        run: dotnet format Web.csproj --verify-no-changes
      - name: Security Scan
        run: dotnet list package --vulnerable
      #- name: Run application
       # run: dotnet run --configuration Release
      - name: Publish Application
        run: dotnet publish -c Release -o publish_output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish_output
        